#
# This workflow maintains the IP Address Management (IPAM) Azure Function by adding IP address ranges to the IPAM storage table.
#

name: Infra-IPAM-Maintain

on:
  push:
    branches: [ none ]
  workflow_dispatch:

jobs:
  maintain-azurefunction:
    runs-on: windows-latest
    steps:
      - name: Check out repository under $GITHUB_WORKSPACE, so job can access it
        uses: actions/checkout@v2

      - name: Log on to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Update Function App
        uses: azure/powershell@v1
        with:
          inlineScript: |      
            function Add-Ipam-Records {
                param (
                    $nwRange,
                    $nwNumber,
                    $nwSize,
                    $nwEnvironment,
                    $nwRegion
                )  
                $orgId = "tim"    
                $mgmtSubName = "mp001"
                $regionId = "uks"
                $faName = "fa-$orgId-$mgmtSubName-$regionId-ipam"
                $faRg = "rg-$orgId-$mgmtSubName-$regionId-ipam"    
                $faId = (Get-AzWebApp -Name $faName -ResourceGroupName $faRg).Id 
                $faFunction = 'Add-IPAM-Range'
                $faFunctionKey = (Invoke-AzResourceAction -ResourceId "$faId/functions/$faFunction" -Action listkeys -Force).default
                $uri = 'https://' + $faName + '.azurewebsites.net/api/' + $faFunction + '?code=' + $faFunctionKey
                $body = @{
                    'InputObject' = @{
                        'NwRange' = $nwRange
                        'NwNumber' = $nwNumber
                        'NwSize' = $nwSize
                        'NwEnvironment' = $nwEnvironment
                        'NwRegion' = $nwRegion
                    }
                } | ConvertTo-Json 
                $params = @{
                    'Uri'         = $uri
                    'Method'      = 'POST'
                    'ContentType' = 'application/json'
                    'Body'        = $body
                }
                Write-Host "Adding" $nwSize "network range" $nwRange "for environment" $nwEnvironment "in region" $nwRegion "-" $nwNumber "records" 
                Invoke-RestMethod @params
            }

            Add-Ipam-Records -nwRange '10.160.0.0' -nwNumber '4' -nwSize 'Small' -nwEnvironment 'Prod' -nwRegion 'uksouth'
            Add-Ipam-Records -nwRange '10.161.0.0' -nwNumber '4' -nwSize 'Medium' -nwEnvironment 'Prod' -nwRegion 'uksouth'
            Add-Ipam-Records -nwRange '10.162.0.0' -nwNumber '4' -nwSize 'Large' -nwEnvironment 'Prod' -nwRegion 'uksouth'
            Add-Ipam-Records -nwRange '10.170.0.0' -nwNumber '4' -nwSize 'Small' -nwEnvironment 'Nonprod' -nwRegion 'uksouth'
            Add-Ipam-Records -nwRange '10.171.0.0' -nwNumber '4' -nwSize 'Medium' -nwEnvironment 'Nonprod' -nwRegion 'uksouth'
            Add-Ipam-Records -nwRange '10.172.0.0' -nwNumber '4' -nwSize 'Large' -nwEnvironment 'Nonprod' -nwRegion 'uksouth'
            Add-Ipam-Records -nwRange '10.180.0.0' -nwNumber '4' -nwSize 'Small' -nwEnvironment 'Prod' -nwRegion 'ukwest'
            Add-Ipam-Records -nwRange '10.181.0.0' -nwNumber '4' -nwSize 'Medium' -nwEnvironment 'Prod' -nwRegion 'ukwest'
            Add-Ipam-Records -nwRange '10.182.0.0' -nwNumber '4' -nwSize 'Large' -nwEnvironment 'Prod' -nwRegion 'ukwest'
            Add-Ipam-Records -nwRange '10.190.0.0' -nwNumber '4' -nwSize 'Small' -nwEnvironment 'Nonprod' -nwRegion 'ukwest'
            Add-Ipam-Records -nwRange '10.191.0.0' -nwNumber '4' -nwSize 'Medium' -nwEnvironment 'Nonprod' -nwRegion 'ukwest'
            Add-Ipam-Records -nwRange '10.192.0.0' -nwNumber '4' -nwSize 'Large' -nwEnvironment 'Nonprod' -nwRegion 'ukwest'
          azPSVersion: latest 
